### ISSUE TITLE
Theme Not Applied to Text Editor

### ISSUE THREAD

**Issue by jusexton** [coeiico/jetbrains-nightfall-theme#20]
After updating to `1.2.0` the theme does not seem to be applied to the text editor portion of the IDE.

![image](https://github.com/coeiico/jetbrains-nightfall-theme/assets/20236003/6503489b-d203-48fb-aca2-68918d0cc37e)

**Comment by coeiico** [comment]
Check if "nightfall" is available in **Settings** > **Editor** > **Color Scheme** under the Scheme dropdown menu

![image](https://github.com/coeiico/jetbrains-nightfall-theme/assets/74169522/3c85dde3-e106-4950-a02b-ba5ba21e5e2f)

**Comment by JayOfferdahl** [comment]
Worked for me, thanks!

**Comment by jusexton** [comment]
> Check if "nightfall" is available in **Settings** > **Editor** > **Color Scheme** under the Scheme dropdown menu

Yep, this solved it. Thank you very much for the speedy response.

**Comment by p0uyaDev** [comment]
ye it worked for me too thanks

**Comment by VasylMartyniv** [comment]
Had the same issue, and fixed by the solution above.

**Comment by crouth-redge** [comment]
More of a workaround than a fix really. If you uninstall this theme and reinstall it, it no longer applies to the text editor unless done manually.. this is a breaking change to the behaviour and not how other themes work. Something is off in the recent update.

**Comment by coeiico** [comment]
> More of a workaround than a fix really. If you uninstall this theme and reinstall it, it no longer applies to the text editor unless done manually.. this is a breaking change to the behaviour and not how other themes work. Something is off in the recent update.

Yes, even reverting the changes doesn't fix the issue on my end. I'll migrate the theme to a more updated approach and hopefully this will solve the issue and mitigate any future problems that may happen

**Comment by mattlibera** [comment]
🧹 cleaning up this issue since this seems resolved for the moment.
